### ISSUE TITLE
Cloud you please show some scripts how to submit your topology to the storm cluster ?

### ISSUE THREAD

**Issue by lynchlee** [yangboz/SpringBootKafkaStorm#1]
Cloud you please show some scripts how to submit your topology to the storm cluster ?
thanks very much .

**Comment by yangboz** [comment]
@lynchlee , this project is in progress, by the way, example code: https://github.com/yangboz/StormCV/blob/master/stormcv-examples/src/nl/tno/stormcv/example/E10_VideoFaceDetectionTopology.java
